model:
  in_channels: 3
  encoder_channels: [32, 64, 128, 256, 512, 1024, 2048]
  encoder_norm: group_norm_32
  encoder_activation: ReLU
  input_size: [512, 512]
  number_of_components: 2
  degrees_of_freedom: 2048
  vector_dim: 2048
  vectorizer_linear_layer_dim: [2048]
  vectorizer_norm: LayerNorm
  vectorizer_activation: ReLU
  rec_dec_channels: [2048,1024, 512, 256, 128, 64, 32, 16]
  rec_dec_first_conv_size: 4
  rec_dec_double_conv: true
  rec_dec_norm: group_norm_32
  rec_dec_activation: ReLU
  rec_dec_output_layer_activation: Sigmoid
  seg_dec_linear_in_neurons: 4096
  seg_dec_linear_out_neurons: 2048
  seg_dec_linear_layer_dim: []
  seg_dec_linear_norm: group_norm_32
  seg_dec_linear_activation: ReLU
  seg_dec_channels: [2048, 1024, 512, 256, 128, 64, 32, 16]
  seg_dec_first_conv_size: 4
  seg_dec_double_conv: true
  seg_dec_norm: group_norm_32
  seg_dec_activation: ReLU
  seg_dec_output_layer_activation: Identity
learning:
  optimizer: Adam
  lr: 0.0001
  epochs: 10
  batch_size: 2
  loss_fn: L1Loss
  vector_similarity_loss: CosineSimilarity
  segmentation_loss: CrossEntropyLoss
  Augmentations:
    degrees: 30
    translate: [0.1, 0.2]
    scale: [0.8, 1.2]
    shear: 15
